//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CALocalMoneyPort.WSItalcambio {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/WSItalcambio.asmx", ConfigurationName="WSItalcambio.WSItalcambioSoap")]
    public interface WSItalcambioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/sendMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information sendMoney(CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney t, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/listSendMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable listSendMoney(CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney[] t, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/getObjectTReceiptElectronicMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney getObjectTReceiptElectronicMoney();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/getObjectInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information getObjectInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/getObjectCredential", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Credencial getObjectCredential();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/getReadtreciptElectronicMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.readtreciptElectronicMoney getReadtreciptElectronicMoney();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/getObjectDivisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Divisa getObjectDivisa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/readMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.readtreciptElectronicMoney readMoney(string KeySender, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/listReadMoney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable listReadMoney(string[] listKeySender, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/addCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information addCurrency(CALocalMoneyPort.WSItalcambio.Divisa d, CALocalMoneyPort.WSItalcambio.Credencial c, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/updateCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information updateCurrency(CALocalMoneyPort.WSItalcambio.Divisa d, CALocalMoneyPort.WSItalcambio.Credencial c, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/checkCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Divisa checkCurrency(string pai_iso3, string codigoDivisa, CALocalMoneyPort.WSItalcambio.Credencial c, string providerAcronym);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/checkCurrencyOnLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Divisa checkCurrencyOnLine(string pai_iso3, string codigoDivisa, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/validateClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information validateClient(string idClient, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/paymentBatchUpdates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable paymentBatchUpdates(CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/updatePaymentDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable updatePaymentDate(CALocalMoneyPort.WSItalcambio.readtreciptElectronicMoney[] t, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/listInformationKeys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable listInformationKeys(string idClient, string idBeneficiary, string sendProviderAcronym, string amount, CALocalMoneyPort.WSItalcambio.Credencial c, string receiptProviderAcronym);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/updateShippingStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information updateShippingStatus(CALocalMoneyPort.WSItalcambio.Credencial c, string keySender, string sendProviderAcronym, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/readTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney readTransaction(string KeySender, CALocalMoneyPort.WSItalcambio.Credencial c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/updateShippingStatusPro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CALocalMoneyPort.WSItalcambio.Information updateShippingStatusPro(CALocalMoneyPort.WSItalcambio.Credencial c, string keySender, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/listDocumentsClient", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable listDocumentsClient(CALocalMoneyPort.WSItalcambio.Credencial c, string idClient, string codeCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WSItalcambio.asmx/listDocumentsClientByAgree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable listDocumentsClientByAgree(CALocalMoneyPort.WSItalcambio.Credencial c, string idClient, string codeCompany, string codAgree);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WSItalcambio.asmx")]
    public partial class tReceiptElectronicMoney : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sendProviderAcronymField;
        
        private string idCompanyField;
        
        private string receiptProviderAcronymField;
        
        private string paymentDateField;
        
        private string sendDateField;
        
        private string pCEnviadoField;
        
        private string iPEnviadoField;
        
        private string paymentDateInCompanyField;
        
        private string idSenderField;
        
        private string firstNameSenderField;
        
        private string secondNameSenderField;
        
        private string lastNameSenderField;
        
        private string secondLastNamerSenderField;
        
        private string idBeneficiaryField;
        
        private string firstNameBeneficiaryField;
        
        private string secondNameBeneficiaryField;
        
        private string lastNameBeneficiaryField;
        
        private string secondLastNameBeneficiaryField;
        
        private string addressBeneficiaryField;
        
        private string cityBeneficiaryField;
        
        private string amountField;
        
        private string countryField;
        
        private string phoneBeneficiaryField;
        
        private string keySenderField;
        
        private string idProviderField;
        
        private string pai_iso3Field;
        
        private string paymenttypeField;
        
        private string bankNameField;
        
        private string bankAddressField;
        
        private string bankCodeField;
        
        private string phoneField;
        
        private string sGroupBranchCodeField;
        
        private string sCurrencyPayCodeField;
        
        private string sBranchCodePayField;
        
        private string currencyCodeField;
        
        private string currencyField;
        
        private string typeAccountField;
        
        private string accountNumberField;
        
        private string idRegionField;
        
        private string abaField;
        
        private string swiftField;
        
        private string ibanField;
        
        private string idAgencyField;
        
        private string agencyField;
        
        private string institutionNumberField;
        
        private string officeNumberField;
        
        private string fixingField;
        
        private string exchangeRateAppliedField;
        
        private string paymentStatusField;
        
        private string aux0Field;
        
        private string aux1Field;
        
        private string aux2Field;
        
        private string aux3Field;
        
        private string aux4Field;
        
        private string currencyPaymentField;
        
        private string emailBeneficiaryField;
        
        private string sendIdAgencyField;
        
        private Information infoField;
        
        private string operationBoxOfficeField;
        
        private string operationCashierField;
        
        private string phoneRemitterField;
        
        private string addressRemitterField;
        
        private string cityRemitterField;
        
        private string stateRemitterField;
        
        private string senderZipCodeField;
        
        private string senderCountryField;
        
        private string stateBeneficiaryField;
        
        private string senderZipCodeBenefField;
        
        private string bankTypeAccountField;
        
        private string emailRemitterField;
        
        private string dateOnBornRemitterField;
        
        private string dIssueIDDateField;
        
        private string sSenderOcupationField;
        
        private string sSourceFundField;
        
        private string sReasonTxtField;
        
        private string sBranchBankCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sendProviderAcronym {
            get {
                return this.sendProviderAcronymField;
            }
            set {
                this.sendProviderAcronymField = value;
                this.RaisePropertyChanged("sendProviderAcronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IdCompany {
            get {
                return this.idCompanyField;
            }
            set {
                this.idCompanyField = value;
                this.RaisePropertyChanged("IdCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string receiptProviderAcronym {
            get {
                return this.receiptProviderAcronymField;
            }
            set {
                this.receiptProviderAcronymField = value;
                this.RaisePropertyChanged("receiptProviderAcronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PCEnviado {
            get {
                return this.pCEnviadoField;
            }
            set {
                this.pCEnviadoField = value;
                this.RaisePropertyChanged("PCEnviado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IPEnviado {
            get {
                return this.iPEnviadoField;
            }
            set {
                this.iPEnviadoField = value;
                this.RaisePropertyChanged("IPEnviado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string paymentDateInCompany {
            get {
                return this.paymentDateInCompanyField;
            }
            set {
                this.paymentDateInCompanyField = value;
                this.RaisePropertyChanged("paymentDateInCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdSender {
            get {
                return this.idSenderField;
            }
            set {
                this.idSenderField = value;
                this.RaisePropertyChanged("IdSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FirstNameSender {
            get {
                return this.firstNameSenderField;
            }
            set {
                this.firstNameSenderField = value;
                this.RaisePropertyChanged("FirstNameSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SecondNameSender {
            get {
                return this.secondNameSenderField;
            }
            set {
                this.secondNameSenderField = value;
                this.RaisePropertyChanged("SecondNameSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LastNameSender {
            get {
                return this.lastNameSenderField;
            }
            set {
                this.lastNameSenderField = value;
                this.RaisePropertyChanged("LastNameSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SecondLastNamerSender {
            get {
                return this.secondLastNamerSenderField;
            }
            set {
                this.secondLastNamerSenderField = value;
                this.RaisePropertyChanged("SecondLastNamerSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string IdBeneficiary {
            get {
                return this.idBeneficiaryField;
            }
            set {
                this.idBeneficiaryField = value;
                this.RaisePropertyChanged("IdBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FirstNameBeneficiary {
            get {
                return this.firstNameBeneficiaryField;
            }
            set {
                this.firstNameBeneficiaryField = value;
                this.RaisePropertyChanged("FirstNameBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SecondNameBeneficiary {
            get {
                return this.secondNameBeneficiaryField;
            }
            set {
                this.secondNameBeneficiaryField = value;
                this.RaisePropertyChanged("SecondNameBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string LastNameBeneficiary {
            get {
                return this.lastNameBeneficiaryField;
            }
            set {
                this.lastNameBeneficiaryField = value;
                this.RaisePropertyChanged("LastNameBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SecondLastNameBeneficiary {
            get {
                return this.secondLastNameBeneficiaryField;
            }
            set {
                this.secondLastNameBeneficiaryField = value;
                this.RaisePropertyChanged("SecondLastNameBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AddressBeneficiary {
            get {
                return this.addressBeneficiaryField;
            }
            set {
                this.addressBeneficiaryField = value;
                this.RaisePropertyChanged("AddressBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CityBeneficiary {
            get {
                return this.cityBeneficiaryField;
            }
            set {
                this.cityBeneficiaryField = value;
                this.RaisePropertyChanged("CityBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PhoneBeneficiary {
            get {
                return this.phoneBeneficiaryField;
            }
            set {
                this.phoneBeneficiaryField = value;
                this.RaisePropertyChanged("PhoneBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string KeySender {
            get {
                return this.keySenderField;
            }
            set {
                this.keySenderField = value;
                this.RaisePropertyChanged("KeySender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
                this.RaisePropertyChanged("IdProvider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string pai_iso3 {
            get {
                return this.pai_iso3Field;
            }
            set {
                this.pai_iso3Field = value;
                this.RaisePropertyChanged("pai_iso3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string paymenttype {
            get {
                return this.paymenttypeField;
            }
            set {
                this.paymenttypeField = value;
                this.RaisePropertyChanged("paymenttype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
                this.RaisePropertyChanged("bankName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string bankAddress {
            get {
                return this.bankAddressField;
            }
            set {
                this.bankAddressField = value;
                this.RaisePropertyChanged("bankAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string bankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("bankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string sGroupBranchCode {
            get {
                return this.sGroupBranchCodeField;
            }
            set {
                this.sGroupBranchCodeField = value;
                this.RaisePropertyChanged("sGroupBranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string sCurrencyPayCode {
            get {
                return this.sCurrencyPayCodeField;
            }
            set {
                this.sCurrencyPayCodeField = value;
                this.RaisePropertyChanged("sCurrencyPayCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string sBranchCodePay {
            get {
                return this.sBranchCodePayField;
            }
            set {
                this.sBranchCodePayField = value;
                this.RaisePropertyChanged("sBranchCodePay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string typeAccount {
            get {
                return this.typeAccountField;
            }
            set {
                this.typeAccountField = value;
                this.RaisePropertyChanged("typeAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string idRegion {
            get {
                return this.idRegionField;
            }
            set {
                this.idRegionField = value;
                this.RaisePropertyChanged("idRegion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string aba {
            get {
                return this.abaField;
            }
            set {
                this.abaField = value;
                this.RaisePropertyChanged("aba");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string swift {
            get {
                return this.swiftField;
            }
            set {
                this.swiftField = value;
                this.RaisePropertyChanged("swift");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string iban {
            get {
                return this.ibanField;
            }
            set {
                this.ibanField = value;
                this.RaisePropertyChanged("iban");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string idAgency {
            get {
                return this.idAgencyField;
            }
            set {
                this.idAgencyField = value;
                this.RaisePropertyChanged("idAgency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string agency {
            get {
                return this.agencyField;
            }
            set {
                this.agencyField = value;
                this.RaisePropertyChanged("agency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string institutionNumber {
            get {
                return this.institutionNumberField;
            }
            set {
                this.institutionNumberField = value;
                this.RaisePropertyChanged("institutionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string officeNumber {
            get {
                return this.officeNumberField;
            }
            set {
                this.officeNumberField = value;
                this.RaisePropertyChanged("officeNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string Fixing {
            get {
                return this.fixingField;
            }
            set {
                this.fixingField = value;
                this.RaisePropertyChanged("Fixing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string exchangeRateApplied {
            get {
                return this.exchangeRateAppliedField;
            }
            set {
                this.exchangeRateAppliedField = value;
                this.RaisePropertyChanged("exchangeRateApplied");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string PaymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
                this.RaisePropertyChanged("PaymentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string Aux0 {
            get {
                return this.aux0Field;
            }
            set {
                this.aux0Field = value;
                this.RaisePropertyChanged("Aux0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string Aux1 {
            get {
                return this.aux1Field;
            }
            set {
                this.aux1Field = value;
                this.RaisePropertyChanged("Aux1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string Aux2 {
            get {
                return this.aux2Field;
            }
            set {
                this.aux2Field = value;
                this.RaisePropertyChanged("Aux2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Aux3 {
            get {
                return this.aux3Field;
            }
            set {
                this.aux3Field = value;
                this.RaisePropertyChanged("Aux3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string Aux4 {
            get {
                return this.aux4Field;
            }
            set {
                this.aux4Field = value;
                this.RaisePropertyChanged("Aux4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string currencyPayment {
            get {
                return this.currencyPaymentField;
            }
            set {
                this.currencyPaymentField = value;
                this.RaisePropertyChanged("currencyPayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string emailBeneficiary {
            get {
                return this.emailBeneficiaryField;
            }
            set {
                this.emailBeneficiaryField = value;
                this.RaisePropertyChanged("emailBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string sendIdAgency {
            get {
                return this.sendIdAgencyField;
            }
            set {
                this.sendIdAgencyField = value;
                this.RaisePropertyChanged("sendIdAgency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public Information info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string operationBoxOffice {
            get {
                return this.operationBoxOfficeField;
            }
            set {
                this.operationBoxOfficeField = value;
                this.RaisePropertyChanged("operationBoxOffice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string operationCashier {
            get {
                return this.operationCashierField;
            }
            set {
                this.operationCashierField = value;
                this.RaisePropertyChanged("operationCashier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string phoneRemitter {
            get {
                return this.phoneRemitterField;
            }
            set {
                this.phoneRemitterField = value;
                this.RaisePropertyChanged("phoneRemitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string addressRemitter {
            get {
                return this.addressRemitterField;
            }
            set {
                this.addressRemitterField = value;
                this.RaisePropertyChanged("addressRemitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string cityRemitter {
            get {
                return this.cityRemitterField;
            }
            set {
                this.cityRemitterField = value;
                this.RaisePropertyChanged("cityRemitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string stateRemitter {
            get {
                return this.stateRemitterField;
            }
            set {
                this.stateRemitterField = value;
                this.RaisePropertyChanged("stateRemitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string senderZipCode {
            get {
                return this.senderZipCodeField;
            }
            set {
                this.senderZipCodeField = value;
                this.RaisePropertyChanged("senderZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string senderCountry {
            get {
                return this.senderCountryField;
            }
            set {
                this.senderCountryField = value;
                this.RaisePropertyChanged("senderCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string stateBeneficiary {
            get {
                return this.stateBeneficiaryField;
            }
            set {
                this.stateBeneficiaryField = value;
                this.RaisePropertyChanged("stateBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string senderZipCodeBenef {
            get {
                return this.senderZipCodeBenefField;
            }
            set {
                this.senderZipCodeBenefField = value;
                this.RaisePropertyChanged("senderZipCodeBenef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string bankTypeAccount {
            get {
                return this.bankTypeAccountField;
            }
            set {
                this.bankTypeAccountField = value;
                this.RaisePropertyChanged("bankTypeAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string emailRemitter {
            get {
                return this.emailRemitterField;
            }
            set {
                this.emailRemitterField = value;
                this.RaisePropertyChanged("emailRemitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string dateOnBornRemitter {
            get {
                return this.dateOnBornRemitterField;
            }
            set {
                this.dateOnBornRemitterField = value;
                this.RaisePropertyChanged("dateOnBornRemitter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public string dIssueIDDate {
            get {
                return this.dIssueIDDateField;
            }
            set {
                this.dIssueIDDateField = value;
                this.RaisePropertyChanged("dIssueIDDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string sSenderOcupation {
            get {
                return this.sSenderOcupationField;
            }
            set {
                this.sSenderOcupationField = value;
                this.RaisePropertyChanged("sSenderOcupation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string sSourceFund {
            get {
                return this.sSourceFundField;
            }
            set {
                this.sSourceFundField = value;
                this.RaisePropertyChanged("sSourceFund");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string sReasonTxt {
            get {
                return this.sReasonTxtField;
            }
            set {
                this.sReasonTxtField = value;
                this.RaisePropertyChanged("sReasonTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public string sBranchBankCode {
            get {
                return this.sBranchBankCodeField;
            }
            set {
                this.sBranchBankCodeField = value;
                this.RaisePropertyChanged("sBranchBankCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WSItalcambio.asmx")]
    public partial class Information : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoField;
        
        private string codigoField;
        
        private string descripcionField;
        
        private string descripcionENField;
        
        private string keySenderField;
        
        private string tasaField;
        
        private string idAgencyField;
        
        private string idProviderField;
        
        private string fechaOrdenField;
        
        private string horaOrdenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescripcionEN {
            get {
                return this.descripcionENField;
            }
            set {
                this.descripcionENField = value;
                this.RaisePropertyChanged("DescripcionEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string keySender {
            get {
                return this.keySenderField;
            }
            set {
                this.keySenderField = value;
                this.RaisePropertyChanged("keySender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tasa {
            get {
                return this.tasaField;
            }
            set {
                this.tasaField = value;
                this.RaisePropertyChanged("tasa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string idAgency {
            get {
                return this.idAgencyField;
            }
            set {
                this.idAgencyField = value;
                this.RaisePropertyChanged("idAgency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string idProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
                this.RaisePropertyChanged("idProvider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string fechaOrden {
            get {
                return this.fechaOrdenField;
            }
            set {
                this.fechaOrdenField = value;
                this.RaisePropertyChanged("fechaOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string horaOrden {
            get {
                return this.horaOrdenField;
            }
            set {
                this.horaOrdenField = value;
                this.RaisePropertyChanged("horaOrden");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WSItalcambio.asmx")]
    public partial class Divisa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigodivisaField;
        
        private string provideracronymField;
        
        private string pai_iso3Field;
        
        private string nombredivisaField;
        
        private string tasaventaField;
        
        private string tasacompraField;
        
        private string fixingField;
        
        private string monedalocalField;
        
        private string diferencialtasaventaField;
        
        private string difrenecialtasacompraField;
        
        private string reguladortasaventaField;
        
        private string reguladortasacompraField;
        
        private string statusDivisaField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigodivisa {
            get {
                return this.codigodivisaField;
            }
            set {
                this.codigodivisaField = value;
                this.RaisePropertyChanged("codigodivisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string provideracronym {
            get {
                return this.provideracronymField;
            }
            set {
                this.provideracronymField = value;
                this.RaisePropertyChanged("provideracronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pai_iso3 {
            get {
                return this.pai_iso3Field;
            }
            set {
                this.pai_iso3Field = value;
                this.RaisePropertyChanged("pai_iso3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nombredivisa {
            get {
                return this.nombredivisaField;
            }
            set {
                this.nombredivisaField = value;
                this.RaisePropertyChanged("nombredivisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tasaventa {
            get {
                return this.tasaventaField;
            }
            set {
                this.tasaventaField = value;
                this.RaisePropertyChanged("tasaventa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tasacompra {
            get {
                return this.tasacompraField;
            }
            set {
                this.tasacompraField = value;
                this.RaisePropertyChanged("tasacompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string fixing {
            get {
                return this.fixingField;
            }
            set {
                this.fixingField = value;
                this.RaisePropertyChanged("fixing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string monedalocal {
            get {
                return this.monedalocalField;
            }
            set {
                this.monedalocalField = value;
                this.RaisePropertyChanged("monedalocal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string diferencialtasaventa {
            get {
                return this.diferencialtasaventaField;
            }
            set {
                this.diferencialtasaventaField = value;
                this.RaisePropertyChanged("diferencialtasaventa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string difrenecialtasacompra {
            get {
                return this.difrenecialtasacompraField;
            }
            set {
                this.difrenecialtasacompraField = value;
                this.RaisePropertyChanged("difrenecialtasacompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string reguladortasaventa {
            get {
                return this.reguladortasaventaField;
            }
            set {
                this.reguladortasaventaField = value;
                this.RaisePropertyChanged("reguladortasaventa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string reguladortasacompra {
            get {
                return this.reguladortasacompraField;
            }
            set {
                this.reguladortasacompraField = value;
                this.RaisePropertyChanged("reguladortasacompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string statusDivisa {
            get {
                return this.statusDivisaField;
            }
            set {
                this.statusDivisaField = value;
                this.RaisePropertyChanged("statusDivisa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WSItalcambio.asmx")]
    public partial class readtreciptElectronicMoney : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idSenderField;
        
        private string nameSenderField;
        
        private string idBeneficiaryField;
        
        private string nameBeneficiaryField;
        
        private string cityBeneficiaryField;
        
        private string amountField;
        
        private string countryField;
        
        private string paymentStatusField;
        
        private string paymentDateField;
        
        private string sendDateField;
        
        private string idProviderField;
        
        private Information infoField;
        
        private string sendProviderAcronymField;
        
        private string sendCountryField;
        
        private string emailBeneficiaryField;
        
        private string phoneBeneficiaryField;
        
        private string addressBeneficiaryField;
        
        private string sendCurrencyField;
        
        private string keySenderField;
        
        private string sendIdAgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdSender {
            get {
                return this.idSenderField;
            }
            set {
                this.idSenderField = value;
                this.RaisePropertyChanged("IdSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nameSender {
            get {
                return this.nameSenderField;
            }
            set {
                this.nameSenderField = value;
                this.RaisePropertyChanged("nameSender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdBeneficiary {
            get {
                return this.idBeneficiaryField;
            }
            set {
                this.idBeneficiaryField = value;
                this.RaisePropertyChanged("IdBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nameBeneficiary {
            get {
                return this.nameBeneficiaryField;
            }
            set {
                this.nameBeneficiaryField = value;
                this.RaisePropertyChanged("nameBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CityBeneficiary {
            get {
                return this.cityBeneficiaryField;
            }
            set {
                this.cityBeneficiaryField = value;
                this.RaisePropertyChanged("CityBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PaymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
                this.RaisePropertyChanged("PaymentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IdProvider {
            get {
                return this.idProviderField;
            }
            set {
                this.idProviderField = value;
                this.RaisePropertyChanged("IdProvider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Information info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string sendProviderAcronym {
            get {
                return this.sendProviderAcronymField;
            }
            set {
                this.sendProviderAcronymField = value;
                this.RaisePropertyChanged("sendProviderAcronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string sendCountry {
            get {
                return this.sendCountryField;
            }
            set {
                this.sendCountryField = value;
                this.RaisePropertyChanged("sendCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string emailBeneficiary {
            get {
                return this.emailBeneficiaryField;
            }
            set {
                this.emailBeneficiaryField = value;
                this.RaisePropertyChanged("emailBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string phoneBeneficiary {
            get {
                return this.phoneBeneficiaryField;
            }
            set {
                this.phoneBeneficiaryField = value;
                this.RaisePropertyChanged("phoneBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string addressBeneficiary {
            get {
                return this.addressBeneficiaryField;
            }
            set {
                this.addressBeneficiaryField = value;
                this.RaisePropertyChanged("addressBeneficiary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string sendCurrency {
            get {
                return this.sendCurrencyField;
            }
            set {
                this.sendCurrencyField = value;
                this.RaisePropertyChanged("sendCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string keySender {
            get {
                return this.keySenderField;
            }
            set {
                this.keySenderField = value;
                this.RaisePropertyChanged("keySender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string sendIdAgency {
            get {
                return this.sendIdAgencyField;
            }
            set {
                this.sendIdAgencyField = value;
                this.RaisePropertyChanged("sendIdAgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WSItalcambio.asmx")]
    public partial class Credencial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sendProviderAcronymField;
        
        private string loginField;
        
        private string passwordField;
        
        private string receiptProviderAcronymField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sendProviderAcronym {
            get {
                return this.sendProviderAcronymField;
            }
            set {
                this.sendProviderAcronymField = value;
                this.RaisePropertyChanged("sendProviderAcronym");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string receiptProviderAcronym {
            get {
                return this.receiptProviderAcronymField;
            }
            set {
                this.receiptProviderAcronymField = value;
                this.RaisePropertyChanged("receiptProviderAcronym");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSItalcambioSoapChannel : CALocalMoneyPort.WSItalcambio.WSItalcambioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSItalcambioSoapClient : System.ServiceModel.ClientBase<CALocalMoneyPort.WSItalcambio.WSItalcambioSoap>, CALocalMoneyPort.WSItalcambio.WSItalcambioSoap {
        
        public WSItalcambioSoapClient() {
        }
        
        public WSItalcambioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSItalcambioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSItalcambioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSItalcambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public CALocalMoneyPort.WSItalcambio.Information sendMoney(CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney t, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.sendMoney(t, c);
        }
        
        public System.Data.DataTable listSendMoney(CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney[] t, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.listSendMoney(t, c);
        }
        
        public CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney getObjectTReceiptElectronicMoney() {
            return base.Channel.getObjectTReceiptElectronicMoney();
        }
        
        public CALocalMoneyPort.WSItalcambio.Information getObjectInformation() {
            return base.Channel.getObjectInformation();
        }
        
        public CALocalMoneyPort.WSItalcambio.Credencial getObjectCredential() {
            return base.Channel.getObjectCredential();
        }
        
        public CALocalMoneyPort.WSItalcambio.readtreciptElectronicMoney getReadtreciptElectronicMoney() {
            return base.Channel.getReadtreciptElectronicMoney();
        }
        
        public CALocalMoneyPort.WSItalcambio.Divisa getObjectDivisa() {
            return base.Channel.getObjectDivisa();
        }
        
        public CALocalMoneyPort.WSItalcambio.readtreciptElectronicMoney readMoney(string KeySender, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.readMoney(KeySender, c);
        }
        
        public System.Data.DataTable listReadMoney(string[] listKeySender, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.listReadMoney(listKeySender, c);
        }
        
        public CALocalMoneyPort.WSItalcambio.Information addCurrency(CALocalMoneyPort.WSItalcambio.Divisa d, CALocalMoneyPort.WSItalcambio.Credencial c, string user) {
            return base.Channel.addCurrency(d, c, user);
        }
        
        public CALocalMoneyPort.WSItalcambio.Information updateCurrency(CALocalMoneyPort.WSItalcambio.Divisa d, CALocalMoneyPort.WSItalcambio.Credencial c, string user) {
            return base.Channel.updateCurrency(d, c, user);
        }
        
        public CALocalMoneyPort.WSItalcambio.Divisa checkCurrency(string pai_iso3, string codigoDivisa, CALocalMoneyPort.WSItalcambio.Credencial c, string providerAcronym) {
            return base.Channel.checkCurrency(pai_iso3, codigoDivisa, c, providerAcronym);
        }
        
        public CALocalMoneyPort.WSItalcambio.Divisa checkCurrencyOnLine(string pai_iso3, string codigoDivisa, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.checkCurrencyOnLine(pai_iso3, codigoDivisa, c);
        }
        
        public CALocalMoneyPort.WSItalcambio.Information validateClient(string idClient, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.validateClient(idClient, c);
        }
        
        public System.Data.DataTable paymentBatchUpdates(CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.paymentBatchUpdates(c);
        }
        
        public System.Data.DataTable updatePaymentDate(CALocalMoneyPort.WSItalcambio.readtreciptElectronicMoney[] t, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.updatePaymentDate(t, c);
        }
        
        public System.Data.DataTable listInformationKeys(string idClient, string idBeneficiary, string sendProviderAcronym, string amount, CALocalMoneyPort.WSItalcambio.Credencial c, string receiptProviderAcronym) {
            return base.Channel.listInformationKeys(idClient, idBeneficiary, sendProviderAcronym, amount, c, receiptProviderAcronym);
        }
        
        public CALocalMoneyPort.WSItalcambio.Information updateShippingStatus(CALocalMoneyPort.WSItalcambio.Credencial c, string keySender, string sendProviderAcronym, string status) {
            return base.Channel.updateShippingStatus(c, keySender, sendProviderAcronym, status);
        }
        
        public CALocalMoneyPort.WSItalcambio.tReceiptElectronicMoney readTransaction(string KeySender, CALocalMoneyPort.WSItalcambio.Credencial c) {
            return base.Channel.readTransaction(KeySender, c);
        }
        
        public CALocalMoneyPort.WSItalcambio.Information updateShippingStatusPro(CALocalMoneyPort.WSItalcambio.Credencial c, string keySender, string status) {
            return base.Channel.updateShippingStatusPro(c, keySender, status);
        }
        
        public System.Data.DataTable listDocumentsClient(CALocalMoneyPort.WSItalcambio.Credencial c, string idClient, string codeCompany) {
            return base.Channel.listDocumentsClient(c, idClient, codeCompany);
        }
        
        public System.Data.DataTable listDocumentsClientByAgree(CALocalMoneyPort.WSItalcambio.Credencial c, string idClient, string codeCompany, string codAgree) {
            return base.Channel.listDocumentsClientByAgree(c, idClient, codeCompany, codAgree);
        }
    }
}
